Lights api
monoDriveIO/monodrive-client pull request #100
Opened 2020-10-07 14:36 UTC by plarios

This PR corresponds to https://github.com/monoDriveIO/simulator-content/pull/111 and https://github.com/monoDriveIO/simulator/pull/305 and includes the configuration structs for the lights api as well as an example of how to use the api

2020-10-09 12:51 UTC, devinaconley requested changes
@plarios - should this be into `development`?

2020-10-13 15:02 UTC, stephendb commented
Please update the PR comment to follow our current convention.
For new controls like this we need to know what the timing is for performance. Please attach to the PR comment.

1. Total Round trip time, and the break down:
- Time spent parsing json
- Time spent waiting on game thread
- Time spent changing lights

2020-10-14 15:08 UTC, bradleynull requested changes
@plarios Just a few minor comments.

2020-10-14 15:08 UTC, bradleynull commented on examples/cpp/lights/lights.cpp
> +    config.simulator["map"] = "Straightaway5k_night";
Suggest moving this to the scenario file and creating your own scenario for this example.

2020-10-15 22:18 UTC, bradleynull requested changes
@plarios Looks good, just one comment.

2020-10-15 22:18 UTC, bradleynull commented on examples/config/scenario_headlights.json
> +  "trigger_boxes": [
The other examples use config files in their own directory if they are not generic. I think this probably needs a refactor to move all config files to more logical spots, but for now can we move these into the lights directory?

2020-10-19 21:40 UTC, bradleynull approved these changes
@plarios This looks good to go after a quick fix to the pathing on the example that I pushed up. Approved!

2020-10-24 13:08 UTC, merged