Jobs module
monoDriveIO/monodrive-client pull request #105
Opened 2020-10-20 19:54 UTC by devinaconley

## Overview
This fully implements the monoDrive jobs API for integration with local and cloud batch processing. This also implements
a waypoint follower example job.

## Changes
- adds jobs configuration parsing
- implements loop batching logic
- adds new waypoint follower example, which uses the jobs module
- adds README to lane follower directory

## Testing
Follow the tutorial here to setup the batch manager:
https://monodrive.readthedocs.io/en/latest/scenario-dashboard/

Follow the README here to test the waypoint c++ example.

Should be able to leave the waypoint example running in a loop, launch a batch from the manager, then see all the jobs processed with results propagated to dashboard.

2020-10-21 16:25 UTC, bradleynull requested changes
@devinaconley I wasn't able to run the looping example for some reason (see my comment). Other than that just some minor cleanup items. Looking good though!

2020-10-21 16:25 UTC, bradleynull commented on examples/cpp/lane_follower/waypoints.cpp
> +float last_throttle = 0;
Depending on what style we want to go with, global values should either be all capitalized or Google style `float kTheNameOfGlobalVariable = 1.0;`

2020-10-21 16:25 UTC, bradleynull commented on examples/cpp/lane_follower/waypoints.cpp
> +    VehicleState* ego = nullptr;
This functionality is already implemented (but it looks like its still in an approved PR): https://github.com/monoDriveIO/monodrive-client/pull/100/files#diff-e9f9c4c9f4c7b2a0637eb95166f97c7d0bf2757c2cc1f8d442c3dafd646408acR368

2020-10-21 16:25 UTC, bradleynull commented on examples/cpp/lane_follower/waypoints.cpp
> +    double dt = last_time ? state->game_time - last_time : 0.1;
Is this guaranteed to work? Testing conditionals on a floating point value can have different outcomes based on architecture.

2020-10-21 16:25 UTC, bradleynull commented on examples/cpp/lane_follower/waypoints.cpp
> +    if (dt) {
Same as comment above. You probably just want to test if `dt` is within some epsilon of 0.

2020-10-21 16:25 UTC, bradleynull commented on monodrive/core/src/Jobs.cpp
> +        std::cerr << "No assets directory provided to locate state file" << std::endl;
Should probably prefix any statements to `cerr` with `ERROR!` or `WARNING!` based on their severity.

2020-10-21 16:25 UTC, bradleynull commented on monodrive/core/src/Jobs.h
> +    bool setState(JobState state);
move to private?

2020-10-21 16:25 UTC, bradleynull commented on monodrive/core/src/Jobs.h
> +    char** argv;
Make a copy instead of a pointer?

2020-10-21 16:25 UTC, bradleynull commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/waypoints --md_simulator examples/config/simulator_straightaway.json --md_scenario examples/config/scenario_multi_vehicle_straightaway.json --md_weather examples/co
For this example I was able to see the ego hit the car in front of it. Not sure if that was expected by the test results showed a failing test which is good. I also see the following output to the terminal, not sure if the blocking call statements are bad:

```
Sensor Connected
Lane deviation exceeded limit: 25.3557 cm. Exiting early.
read: A blocking operation was interrupted by a call to WSACancelBlockingCall
read: A blocking operation was interrupted by a call to WSACancelBlockingCall
```

2020-10-21 16:25 UTC, bradleynull commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/waypoints --md_assets ./assets_dir --md_loop
For this example I keep getting an error from the `assets_dir` even if I created by hand before running: 

```
$ ./build/examples/cpp/lane_follower/Release/waypoints.exe --md_assets ./assets_dir --md_loop
Wed, 21 Oct, 2020 11:23:26
Unable to read state file: ./assets_dir\STATUS
status:
Unable to read state file: ./assets_dir\STATUS
status:
```

2020-10-21 16:25 UTC, bradleynull commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/real_time
All of these examples will be in the `Release` (or `Debug`) directory on Windows. You probably want to note that. e.g.

```
./build/examples/cpp/lane_follower/Release/real_time.exe
```

2020-10-21 16:42 UTC, devinaconley commented on examples/cpp/lane_follower/README.md
> +This example also configures a Lidar sensor and forwards packets for visualization in VeloView.Otherwise this is the same as the fixed time step example described above.
Fixed

2020-10-21 16:44 UTC, devinaconley commented on examples/cpp/lane_follower/waypoints.cpp
> +float last_throttle = 0;
Agreed. Can we kick that to a larger discussion on style across the whole repo?

2020-10-21 16:44 UTC, devinaconley commented on examples/cpp/lane_follower/waypoints.cpp
> +    VehicleState* ego = nullptr;
That function looks similar, but still need to iterate to find the actual object within the state sensor frame

2020-10-21 16:54 UTC, devinaconley commented on examples/cpp/lane_follower/waypoints.cpp
> +    double dt = last_time ? state->game_time - last_time : 0.1;
fixed

2020-10-21 16:54 UTC, devinaconley commented on examples/cpp/lane_follower/waypoints.cpp
> +    if (dt) {
addressed

2020-10-21 16:58 UTC, devinaconley commented on monodrive/core/src/Jobs.cpp
> +        std::cerr << "No assets directory provided to locate state file" << std::endl;
addressed

2020-10-21 16:59 UTC, devinaconley commented on monodrive/core/src/Jobs.h
> +    bool setState(JobState state);
fixed

2020-10-21 17:18 UTC, devinaconley commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/waypoints --md_simulator examples/config/simulator_straightaway.json --md_scenario examples/config/scenario_multi_vehicle_straightaway.json --md_weather examples/co
Did the ego hit that car in front of it before or after that lane deviation was thrown?

2020-10-21 17:18 UTC, devinaconley commented on monodrive/core/src/Jobs.h
> +    char** argv;
Going to leave this as is to keep it simple. We aren't modifying those values, and we get to do parsing before the UUT code touches it

2020-10-21 17:19 UTC, devinaconley commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/waypoints --md_assets ./assets_dir --md_loop
This is a benign warning, because the batch tool hasn't been run yet. I updated the error to be more clear

2020-10-21 17:22 UTC, devinaconley commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/real_time
noted

2020-10-21 17:23 UTC, devinaconley commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/waypoints --md_simulator examples/config/simulator_straightaway.json --md_scenario examples/config/scenario_multi_vehicle_straightaway.json --md_weather examples/co
Actually nevermind.. realized I accidentally increased the target speed. Fixed now

2020-10-21 17:28 UTC, devinaconley commented
@bradleynull -- thanks for the thorough review! Comments addressed

2020-10-27 19:24 UTC, bradleynull commented on examples/cpp/lane_follower/waypoints.cpp
> +float last_throttle = 0;
Lead by example? Can we change it here and put an issue in?

2020-10-27 19:25 UTC, bradleynull commented on examples/cpp/lane_follower/waypoints.cpp
> +    VehicleState* ego = nullptr;
Looks like this was merged. Can we extend this function to do the same functionality?

2020-10-27 20:17 UTC, bradleynull commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/waypoints --md_assets ./assets_dir --md_loop
I got the latest batch manger built and running but I couldn't seem to get it to run this example:

```
$ ./build/examples/cpp/lane_follower/Release/waypoints.exe --md_assets ~/Documents/GitHub/simulator-python-client/batch_manager --md_loop
Tue, 27 Oct, 2020 15:11:11
Job status: READY
WARNING! Unable to read configuration file at: C:/Users/bradn/Documents/GitHub/simulator-python-client/batch_manager\scenario.json
```

I uploaded the `straightaway_scenario.json` used by the other examples in the manger and it keeps looking for `scenario.json`. However, when I upload `scenario.json` the batch manager just hangs.

2020-10-27 20:18 UTC, bradleynull commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/real_time
I don't see this mentioned in the README?

2020-10-27 20:20 UTC, bradleynull requested changes
@devinaconley Still some questions about previous issues and one minor documentation change. Let me know when you're ready for another look!

2020-10-27 20:20 UTC, bradleynull commented on examples/cpp/lane_follower/README.md
> +Note that on Windows, these examples will be built to the `Debug` or `Release` folder`
Could we make this a big bold note that refers to all examples near the top. Maybe in the intro section?

2020-10-28 21:13 UTC, devinaconley commented on examples/cpp/lane_follower/waypoints.cpp
> +float last_throttle = 0;
updated

2020-10-28 21:43 UTC, devinaconley commented on examples/cpp/lane_follower/waypoints.cpp
> +    VehicleState* ego = nullptr;
We still need to iterate over the state sensor list either way to get the actual vehicle pose out anyways

Don't think there's enough overlap with the purpose of that other function to modify the core lib

Also a good example of parsing data from the state sensor

2020-10-28 21:43 UTC, devinaconley commented on examples/cpp/lane_follower/README.md
> +./build/examples/cpp/lane_follower/waypoints --md_assets ./assets_dir --md_loop
I think we got this part sorted yesterday? @katiemacaulay

2020-10-28 21:43 UTC, devinaconley commented on examples/cpp/lane_follower/README.md
> +Note that on Windows, these examples will be built to the `Debug` or `Release` folder`
yes done

2020-10-28 21:45 UTC, devinaconley commented
Think this is ready for another look @bradleynull !

2020-10-30 13:49 UTC, bradleynull approved these changes
@devinaconley This looks good to go for me. Approved!

2020-10-30 19:06 UTC, merged