Distributed viewport update
monoDriveIO/monodrive-client pull request #106
Opened 2020-10-21 16:26 UTC by devinaconley

## Overview
This updates the distributed example to configure camera viewports with the new method

## Changes
- configure a `Camera` sensor with a nested `Viewport` object
- modify camera position on vehicle
- bug fix to not wait for sensors that aren't streaming

## Testing
Launch simulators on ports 8999, 9000, 9001

Run the distributed example

Should see two viewports open up displaying a front right and front left camera view

2020-10-21 16:38 UTC, bradleynull requested changes
@devinaconley This is working for me. I was curious if we could make the example start the viewports in "windowed" mode so we have a window border and title? Mine just pop up and are not movable: 
![image](https://user-images.githubusercontent.com/6026642/96750678-d898a480-1391-11eb-8715-3821a4e73206.png)

Other than that, just one other minor comment.

2020-10-21 16:38 UTC, bradleynull commented on examples/cpp/distributed/replica_lidar_sensors.json
> +    "viewport": {
We need an issue in the documentation repo to update all the camera configuration examples after this is merged.

2020-10-27 15:59 UTC, devinaconley commented on examples/cpp/distributed/replica_lidar_sensors.json
> +    "viewport": {
Yep I have an issue for myself on this one

2020-10-27 16:16 UTC, devinaconley commented
@bradleynull - pushed the windows slightly off the top border, should be able to move them now!

2020-10-27 19:21 UTC, bradleynull approved these changes
@devinaconley Looks good to go now. Approved!

2020-10-28 18:47 UTC, merged