Speed curve example
monoDriveIO/monodrive-client pull request #113
Opened 2020-11-03 14:43 UTC by devinaconley

## Overview
This PR implements a target speed curve example with the PID controller. The example loads up a CSV file of time series speed data, and dynamically feeds these values to the PID controllers as the target speed. It also dumps results to file for further analysis. This addresses #107.

## Changes
- adds `speed_curve.cpp` example within the `lane_follower` example set
- adds mock speed curve data (generated programmatically)
- updates readme
- new solo straightaway scenario
- handles zero speed case

## Testing
Build and run the `speed_curve` example. Should see the vehicle smoothly accelerate up to 20 m/s before slowing back to a stop. There should also be an output file generated called `speed_curve_reproduced.csv`. This can be examined to ensure curves match relatively well.

2020-11-03 14:49 UTC, devinaconley commented
Example comparison of mock vs reproduced data
![speed_curve_comparison](https://user-images.githubusercontent.com/15223693/97999833-6ec8c380-1db1-11eb-92e0-f207ba6146ab.png)

2020-11-03 16:16 UTC, bradleynull requested changes
@devinaconley Just some minor cleanup and a bug fix for Windows. Everything seems to be working for me though.

2020-11-03 16:16 UTC, bradleynull commented on examples/cpp/lane_follower/speed_curve.cpp
> +#include "eigen3/Eigen/Dense"
This is the wrong include for Windows. Should be

```
#include <Eigen/Eigen>
```

2020-11-06 20:52 UTC, devinaconley commented on examples/cpp/lane_follower/README.md
> +data in order to compare or calibrate the vehicle physics model used in the simulator.
added

2020-11-06 20:53 UTC, devinaconley commented on examples/cpp/lane_follower/speed_curve.cpp
> +    MatrixXd data = read_csv<MatrixXd>("examples/cpp/lane_follower/speed_curve_data.csv");
is that somewhat matlab centric?

2020-11-06 21:00 UTC, devinaconley commented on examples/cpp/lane_follower/speed_curve.cpp
> +#include "eigen3/Eigen/Dense"
fixed :+1:

2020-11-06 21:02 UTC, devinaconley commented
@bradleynull - ready for another look!

2020-11-09 16:38 UTC, devinaconley commented
@bradleynull - addressed that last comment! Good another look.

2020-11-12 20:13 UTC, bradleynull approved these changes
@devinaconley Looks good to go. Approved!

2020-11-12 20:22 UTC, merged