Cleanup for 0.4 release
monoDriveIO/monodrive-client pull request #129
Opened 2021-01-29 22:42 UTC by devinaconley

## Overview
This PR includes various configuration and stability fixes before tagging `0.4.0`

## Changes
- update documentation and readme
- fixes for scenario and weather configs
- clean up old example
- upgrade lane follower batch job example to use opendrive api

## Testing
- build and run various examples, ensure stable expected output
- follow README under `examples/cpp/diagnostics` to run external test suite
- trying running lane follower `lane_keep` job example

2021-02-01 15:28 UTC, stephendb commented
This is fine but was expecting more in way of cleanup. We need to clear up a lot of erroneous comments and commands still like the statement that a vehicle control is necessary to spawn a vehicle which it is not.

2021-02-09 10:26 UTC, devinaconley commented
@stephendb took another pass at cleanup, specifically on the `dev` examples. Good for another look

2021-02-10 23:24 UTC, citlaligm requested changes
@devinaconley looking good. Just some small comments here.

2021-02-10 23:24 UTC, citlaligm commented on examples/cpp/dev/ultrasonic_sensor.cpp
> +    u_config.location.x = 200.f;
The location for the ultrasound seems a little bit off. 
![image](https://user-images.githubusercontent.com/10260895/107584140-9eae1100-6bc1-11eb-9833-dd8aebce0320.png)

2021-02-10 23:24 UTC, citlaligm commented on examples/cpp/lane_follower/lane_keep.cpp
>  // against the monoDrive simulator in closed loop mode
When I rant his example I couldn't see anything happening, I got this message on the console. Am I missing something here?  
![image](https://user-images.githubusercontent.com/10260895/107585146-50017680-6bc3-11eb-87fe-df271da118ef.png)

2021-02-10 23:24 UTC, citlaligm commented on examples/cpp/diagnostics/README.md
> +./build/examples/cpp/diagnostics/Release/simulator_test.exe
For Windows seems a little bit different the path or are the swap maybe? 
![image](https://user-images.githubusercontent.com/10260895/107585807-7a9fff00-6bc4-11eb-8f3e-e69933508ff1.png)

2021-02-11 00:05 UTC, devinaconley commented on examples/cpp/dev/ultrasonic_sensor.cpp
> +    u_config.location.x = 200.f;
Left it a bit forward in case a user swaps in another vehicle

2021-02-11 00:07 UTC, devinaconley commented on examples/cpp/lane_follower/lane_keep.cpp
>  // against the monoDrive simulator in closed loop mode
Checkout  `examples/cpp/lane_follower/README.md` for how to run this one . Might be missing a command line argument

2021-02-11 00:11 UTC, devinaconley commented on examples/cpp/diagnostics/README.md
> +./build/examples/cpp/diagnostics/Release/simulator_test.exe
Good catch, fixed

2021-02-11 00:11 UTC, devinaconley commented
Thanks @citlaligm - should be good for another look

2021-02-11 16:11 UTC, citlaligm commented on examples/cpp/lane_follower/lane_keep.cpp
>  // against the monoDrive simulator in closed loop mode
Is this the expected output? it starts running and after 4-5 sec I see this message:
![image](https://user-images.githubusercontent.com/10260895/107662034-7bca3e00-6c4f-11eb-8447-e1f7d7c4b989.png)

Also, I noticed that I don't get the Release folder on the builds, all the paths on the README, point to the Release version.  Is there a flag or something for these.

2021-02-11 16:20 UTC, citlaligm reviewed
Other than the lane keep comment I added. Looks good to me.

2021-02-11 16:59 UTC, devinaconley commented on examples/cpp/lane_follower/lane_keep.cpp
>  // against the monoDrive simulator in closed loop mode
I think this depends on what mode you are in, you can replace "Release" with "Debug"

2021-02-11 17:00 UTC, devinaconley commented on examples/cpp/lane_follower/lane_keep.cpp
>  // against the monoDrive simulator in closed loop mode
The jobs runs for 10 seconds, if no lane deviation has occurred, it will exit successfully

2021-02-11 17:04 UTC, citlaligm commented on examples/cpp/lane_follower/lane_keep.cpp
>  // against the monoDrive simulator in closed loop mode
> I think this depends on what mode you are in, you can replace "Release" with "Debug"
Yeah, I replaced Release with Debug to run,  but just wondering how to compile the Release versions and if we should include instructions on how to do that so we minimize confusion  for end users.

2021-02-11 17:04 UTC, citlaligm approved these changes

2021-02-11 17:08 UTC, merged