Ros bridge additions
monoDriveIO/monodrive-client pull request #90
Opened 2020-09-10 20:14 UTC by plarios

This PR includes a `MessageFactory` class under `monodrive/ros/src/monodrive_msgs/include` that provides functions to facilitate converting messages from the monoDrive sensor frame format to their ROS counterparts, and vice-versa. It also adds a new ROS example based on @bradleynull's `distributed` C++ example, which takes the sensor data, uses the message conversion class to convert the messages to ROS messages, and publishes those messages on a specific topic.

2020-09-14 23:43 UTC, bradleynull requested changes
@plarios Just some minor cleanup comments and can we put the `launch.json` back? I don't know if we want to force customers to figure that out, or at least we should add some info to the README on how to do it.

2020-09-14 23:43 UTC, bradleynull commented on examples/cpp/distributed/distributed.cpp
> +      // std::make_shared<ReplicaDistributedServer>(replica_radar_config,
Uncomment?

2020-09-14 23:43 UTC, bradleynull commented on examples/cpp/distributed/distributed.cpp
> +  Event* replicasReadyEvent = new Event(int(replicaServers.size()));
This isn't used anymore right? Also its not being deleted if it is used.

2020-09-14 23:43 UTC, bradleynull commented on monodrive/core/src/DistributedServer.cpp
> +#pragma optimize("", off)
Can you put a comment here on why this is necessary?

2020-09-14 23:43 UTC, bradleynull commented on monodrive/core/src/DistributedServer.cpp
> +    //sampleComplete->wait();
Remove.

2020-09-14 23:43 UTC, bradleynull commented on monodrive/core/src/DistributedServer.h
> +        }
Is the event class still necessary? Should we just remove?

2020-09-30 01:31 UTC, stephendb requested changes
Besides Brad's cleanup comment, need to delete the control message, this is handled differently on development with a subscription and callback.

2020-09-30 01:31 UTC, stephendb commented on examples/ros/src/distributed/src/distributed.cpp
> +    server->sendCommand(ego_control_config.message());
This is handled in a callback and can be deleted, see current distributed.cpp.

2020-09-30 22:45 UTC, stephendb requested changes
Couple minor things on Radar. We need a performance comparison with/without the ROS conversions using the GPU allocation update later.

2020-09-30 22:45 UTC, stephendb commented on monodrive/ros/src/monodrive_msgs/include/MessageFactory.h
> +            for (auto& value : radarCubeFrame.radar_cube) {
Is this something we can do a bulk copy one line? What is the memory alignment? At a minimum we can pre-allocate the vector rather than using push_back.

2020-09-30 22:45 UTC, stephendb commented on monodrive/ros/src/monodrive_msgs/include/MessageFactory.h
> +                result.targets.push_back(RadarTargetToROSRadarTarget(target));
Can we pre-allocate "reserve" and use emplace_back. Should help with conversion speed.

2020-10-02 21:15 UTC, stephendb approved these changes

2020-10-02 21:15 UTC, merged