Generic viewport
monoDriveIO/monodrive-client pull request #91
Opened 2020-09-11 23:05 UTC by devinaconley

- refactor viewport configuration to be a nested struct within the camera config
- viewport now supported for Camera, 360 Camera, and Fisheye Camera
- updates `multi_viewport.cpp` example to show a 360 Camera example

2020-09-14 22:46 UTC, bradleynull requested changes
@devinaconley Just one question about the data structures. Let me know if you want to go through this together to help me understand better.

2020-09-14 22:46 UTC, bradleynull commented on monodrive/core/src/sensor_config.h
> +struct ViewportConfig
Why does this not inherit from the base sensor? Is the idea that this is just used in the camera config and is always there by default? If that's the case, can we subclass this from `CameraConfig`? 

In looks like this is just a data structure to be included with cameras. If the above isn't an option, can we rename this to `ViewportStruct` or something similar so that it is not confused with a sensor conifg? This way customers will not be confused.

2020-09-15 14:42 UTC, devinaconley commented on monodrive/core/src/sensor_config.h
> +struct ViewportConfig
Originally this was an inherited class. For more flexibility across generic camera types, moved to using a nested struct object with configures the viewport, similarly to how the annotation system works.

Agree with your suggestion and renamed the struct to `Viewport`

2020-09-15 14:49 UTC, bradleynull approved these changes
@devinaconley Looks good to go. Approved!

2020-09-15 14:51 UTC, merged